version: '3'

volumes: 
  data: {}

services: 
  nginx:
    image: debian:buster 
    restart: always
    ports:
      - "443:443" 
    volumes:
      - data:/var/www/html
    networks:
      - sparkworld
    tty: true

  wordpress:
    image: debian:buster
    restart: always
    volumes: 
      - data:/var/www/html
    expose:
      - "9000"
    networks:
      - sparkworld
    tty: true

  mariadb:
    image: debian:buster
    restart: always
    expose: 
      - "3306"
    networks:
      - sparkworld
    tty: true


networks: 
  sparkworld:
    driver: bridge 
